import englishSummersImage from '../images/english-summers-image.jpg'

export default {
  slug: 'english-summers',       // used in the URL: /article/your-slug
  title: 'English Summers',
  date: 'Jul 6, 2026',     // anything Date.parse() understands; used for sort order
  content: (
    <>
      <img src={englishSummersImage} alt="English Summers" />
      <p>It is not a new thought that English summers are sublime. It has been thought by many others many times before, and I’m sure will be thought by many others many times to come. But here and now I know in my deepest soul that England in the summer is the best place on Earth, and I must write it down.</p>
      <p>Yesterday, I got the train to London for my friend’s American independence day picnic in Regent’s Park. We sat on the grass, drank Budweiser and ate hot dogs that he had boiled the morning before and brought with him on the train wrapped in tin foil and a tea towel. A UK national as well as a US citizen, he also provided strawberries, pork pies, and scotch eggs - situating the affair somewhere in the middle of the Atlantic. The sun was out, it was not sweltering, and we saw the Goodyear blimp fly past at least twice. Friends of friends came and went, and London locals sauntered, jogged, and tennis-ed past near where we sat for 6 hours. A “festival of music” was happening at the bandstand, and families lounged in lawn chairs eating soft serve ice cream. Ducks and geese filled the lake, and ducklings and goslings paddled behind their parents towards the bread offered by park goers. By all accounts it was a scene plucked from an idyllic mid-century English novel. I can conceive of nothing else I would have rather done with my Sunday.</p>
      <p>Before Regent’s, on Saturday, I went to Henley Royal Regatta and watched Oliver Zeidler be ridiculously good at rowing on the river Thames. Picturesque Henley is woefully ill-equipped to handle the throngs of rowers, tourists, locals, Londoners, and members of the wider hobnobbing élite that descend to watch the athletes push very hard on the water. Even more exhausted than those racing were the bottle-necked crowds waiting to get between the posh and pricey enclosures near the bridge and the riverbank where all the food is sold. We got stuck there for 30 minutes on the way down, and 40 minutes on the way back up. Despite this minor lapse in foresight by the event planning committee, the day went off without a hitch. The great and the good wore feverishly coloured blazers, repping rowing clubs from around the UK and beyond. Ladies and gentlemen showed off their vintage Rolls-Royces from behind riverside fences. Bass boosted dance music for the schoolgirl/boy rowers of the tournament abounded, and food vans selling overpriced smash burgers for £17 crowded for space on the narrow riverbank. And the English-British-International public loved every bit of it, myself included. Turns out that sweating through your shirt surrounded by tipsy rowing fanatics and drinking Pimms from a can is a supreme pastime. Rowing isn’t even that exciting to watch. The boats just go in a straight line! Classic English affair.</p>
      <p>To top it all off, last night we beat Mexico at the Azteca stadium to crowded pubs open until 5am. The late prime minister even passed extra-special legislation overruling the 11pm licensing laws just for the footy. And now, sat in a flat built in the late 1800s, and designed to keep the heat in, not out, I write this brief article expressing my love for it all. English summers are superbly silly. They are filled with hoards and sweat and there’s no AC in sight. Nor should there be! It would go against the English spirit to be entirely comfortable - that’s the point. The point of an English summer is to go to silly events, dressed in silly clothing, and watch silly games, sports, music, shows, people, life and whatever other means of brilliant entertainment this overcrowded island nation can provide us, all whilst too hot and too bothered to think straight. English summer will never fail to deliver. Bring on the second half.</p>
    </>
  ),
}