import goodCoffeeImage from '../images/good-coffee-bad-coffee-image.jpg'

export default {
  slug: 'good-coffee-bad-coffee',       // used in the URL: /article/your-slug
  title: 'Good Coffee is Expensive, Bad Coffee is Too',
  date: 'Jul 25, 2026',     // anything Date.parse() understands; used for sort order
  content: (
    <>
      <img src={goodCoffeeImage} alt="English Summers" />
      <p>Today I have had one cup of coffee. This morning, I wandered over to my coffee grinder, poured some beans into it, ground them with ear-splitting imprecision, boiled some water, put the beans into my pour-over filter, poured the water in, let it drip, added some milk, and drank. It was nice. It was nice and it took 9 steps not including buying the beans yesterday or the mandatory pre-coffee shower routine I’ve got going on. A solid effort.</p>
      <p>My coffee grinder is new. I bought it for £25 at the Great British institution that is John Lewis & Partners. It’s fine, it has a blade, the blade goes round, and kind of mashes up the coffee beans into a not-so-fine powder that can be dumped into my Hario V60 and brewed. I am reliably informed by British Barista Champion 2007 James Hoffman that “blade grinders” are not all that good. I didn’t believe him and bought one. Now that I have one, I believe him.</p>
      <p>After all the hot water has dripped through, the detritus left behind is visibly uneven. Not an obviously bad thing I don’t think. Problem is I know it shouldn’t look like that. The pre-ground coffee that I have been buying for years at the supermarket has detritus which is distinctly uniform in nature. Soft spoken Barista-king James Hoffman tells me this is good. It means that all of the grounds get an even “extraction” and so the coffee captures more of what the beans taste like at their best. Now I’m not sure how much of this pure theory I can truly buy into, but I think I do agree that the coffee tastes worse if its not evenly ground. Whether that’s just a placebo effect is hard to know, but I prefer the taste of the supermarket pre-ground stuff at present to the coffee produced by my blade ground beans. Even though the beans cost 2x as much. Sad. It looks like that £25 was a waste.</p>
      <p>Supposedly what I need to avoid this fate is a “burr” grinder. The cheapest “good” burr grinders are roughly £50-100, and if you want an electric one they’re closer to £150. Pricey stuff! Until recently this was only a concept delivered to me via Youtube videos. Last week it bled over into reality when I went to a family friend’s house, where I was shown an expensive electric burr grinder in the flesh. The family friend even agreed that blade grinders were no good when I mentioned my plight. Everyone knew but me! </p>
      <p>But! I like grinding my coffee. I like my invasively loud and shit blade grinder. I like buying distinctive bags of unground coffee from quaint local coffee shops. It smells nice in the morning even if the final output is allegedly and actually worse. £25 is a good stepping stone I’ve decided. A bag of “specialty” coffee beans, the kind I’ve been buying more and more of recently, costs somewhere between £10-20 a bag, which lasts me about 2 weeks. So I’m operating at a ~1:1 ratio. The price of my coffee grinder, which hypothetically I could use to grind infinite bags of expensive artisan coffee, is on the same order of magnitude as a single bag of the stuff. Probably this is why my brew does not taste incredible, because of misallocated capital investment. However, I’m not sure I believe any coffee, ground any which way, would ever truly be mind blowing. I’m not convinced I’ve ever had a transcendental experience due to dirty bean water even at a fancy café. Nor am I convinced anyone else has regardless of the price or quality. </p>
      <p>That being said, you don’t know unless you try. Check back soon for my £150 coffee grinder review.</p>
    </>
  ),
}